### PR TITLE
Change WebRTC to my own hosted ( im sharing it to others )

### PR DESCRIPTION
**Pull request by Bartixxx32**
I have created this pull request to help people that have problem with WebRTC setup or using zap-hosting this change autmaticly making phone using my vps located in EU Germany with 1/GBs up/down link :)

### CODE REVIEW

**Comment by Gannon001** [comment]
Thank you for sharing <3

**Comment by Fireant456** [comment]
https://github.com/N3MTV/gcphone/issues/220 I am still having issues even when trying to use your server...

**Comment by Bartixxx32** [comment]
> #220 I am still having issues even when trying to use your server...

It should work no problem on server site mate :)
image

**Comment by Bartixxx32** [comment]
I will also note that server restart every 3am GMT+1 restart take +- 30 secs i hope that not the problem :)

**Comment by Bartixxx32** [comment]
> Thank you for sharing <3

Can I ask you to issue this pull request for the releases tab?  because many users do not look at pullrequests :)

**Comment by KingWalnut** [comment]
females on my server using female peds cant hear/ or be heard by people on the phone using webrtc?

**Comment by wolgix** [comment]
Doesnt work anymore

**Comment by Bartixxx32** [comment]
new adress. webrtc.needrp.net

**Comment by Maxx016** [comment]
New address not working? :/

**Comment by krhuy1996** [comment]
how i can host new rtc?

**Comment by KamorakRP** [comment]
doesnt working anymore

**Pull request merged**
