### PR TITLE
Minor cleanup + Support for newest ESX

### PR DESCRIPTION
**Pull request by rex2630**

### CODE REVIEW

**Comment by rex2630** [comment]
Not best option, but it works

**Comment by m0iises19** [comment]
this error comes out

Sin título

```
function getPlayerID(source)
    local xplayer = ESX.GetPlayerFromId(source)
    local player = xplayer.identifier
    return player
end
```

**Comment by rex2630** [comment]
I know, but why do u care? It works doesnt it?

**Comment by rex2630** [comment]
@m0iises19 Try now. Should be ok :)

**Comment by m0iises19** [comment]
```
-- Just For reload
RegisterServerEvent('gcPhone:allUpdate')
AddEventHandler('gcPhone:allUpdate', function()
    local sourcePlayer = tonumber(source)
	local xplayer = ESX.GetPlayerFromId(source)
    local identifier = xplayer.identifier
    local num = getNumberPhone(identifier)
    TriggerClientEvent("gcPhone:myPhoneNumber", sourcePlayer, num)
    TriggerClientEvent("gcPhone:contactList", sourcePlayer, getContacts(identifier))
    TriggerClientEvent("gcPhone:allMessage", sourcePlayer, getMessages(identifier))
    TriggerClientEvent('gcPhone:getBourse', sourcePlayer, getBourse())
    sendHistoriqueCall(sourcePlayer, num)
end)
```

Sin título

**Comment by rex2630** [comment]
Are u using kashacters?

**Comment by m0iises19** [comment]
@rex2630 no

**Comment by rex2630** [comment]
This should be used on client side: https://esx-org.github.io/es_extended/client/events/playerloaded/

**Comment by rex2630** [comment]
Ok, that not actually true what i said. We can use that. I will try to fix it later

**Comment by polarim** [comment]
ah, you just removed getplayerid altogether, i wanted to but i was lazy and just modified it to 
`function getPlayerID(source)
	local srcPlayer = ESX.GetPlayerFromId(source)
	if srcPlayer ~= nil then
		return srcPlayer.identifier
	else
		return nil
	end
end`

lol.

tbh, still doesn't stop the whole 'OnResourceStart' whenever someone joins the server, the first index of xPlayer is going to be nil because the resource loads before xPlayer is initiated. 🤷‍♂ 

actually, because of that, it's like doing twice the work for someone who already has a phone number iirc.  running AllUpdate and 'playerLoaded' so idk, Idc enough to fix it because it works so lol

**Comment by polarim** [comment]
Latest commit should be unnecessary, no need for a wait on if playerLoaded = true because esx:playerLoaded only activates when xPlayer is initiated/loaded by esx, so the if statement is doing what that event does for it @rex2630

**Comment by rex2630** [comment]
Idk, try it and tell me whats needed and whats not. I think we need both

**Comment by polarim** [comment]
for me, esx:playerLoaded works fine without the wait afaik, but you changed a lot more than I have in my gcphone.  i think that wait would be best for 'allUpdate' though because OnResourceStart tries to run that before you even exist.

**Comment by rex2630** [comment]
So does it work all as it is now?

**Comment by polarim** [comment]
When I get a chance, I can try to throw this version of gcphone in my test server and try it out

**Comment by m0iises19** [comment]
Now it seems to be all right, but the messages to the jobs don't work

**Comment by rex2630** [comment]
What? They are working alright

**Comment by m0iises19** [comment]
Yes, it generates the number and I do not see errors in the console, only that the messages to the work does not work

**Comment by rex2630** [comment]
U are doing something wrong. Because it works just fine. Bad config or something and dont forget about esx_addons for gcphone.

**Comment by m0iises19** [comment]
ok I saw the error, this update is wrong

https://github.com/N3MTV/gcphone/pull/305/commits/4aa7369388d793379381c3fbfb3f5e9b39b65dea

it should be like this to make it work well:

```
fx_version 'adamant'

game 'gta5'

client_script {
	"client.lua"
}

server_script {
	'@mysql-async/lib/MySQL.lua',
	"server.lua"
}


-- {
-- 	"display": "Police",
-- 	"subMenu": [
-- 		{
-- 			"title": "Envoyer un message",
-- 			"eventName": "esx_addons_gcphone:call",
-- 			"type": {
-- 				"number": "police"
-- 			}
-- 		}
-- 	]
-- }
```

**Comment by rex2630** [comment]
Ok, thanks. Should be all fine now. This is longest PR ever i think :D

**Comment by m0iises19** [comment]
@rex2630  thanks to you for helping so much in this script

**Comment by polarim** [comment]
gcphone has so much bloat in it lol

**Comment by rex2630** [comment]
yeah, i know. Thats why i wanted to clean it just a little bit

**Comment by Rhydium** [comment]
I hope this gets merged, this looks promising.

**Comment by rex2630** [comment]
I have seen that bank needs to be  fixed too. I would like to fix it. I will see how it goes

**Comment by zetRk** [comment]
After trying all of these, i got the phone to almost work properly, 1 issue remains, somehow the camera from the phone is broken. Any ideas?

**Comment by NightcoreIsla** [comment]
the phone take out animation didn't generate phone object at this version
it like player watch at empty hand now

**Comment by NightcoreIsla** [comment]
i find the fix way,
the fxmainfest.lua is not support for phone model load,seem fivem loading src problem
need use __resource.lua instead for it

**Comment by Rhydium** [comment]
> i find the fix way,
> the fxmainfest.lua is not support for phone model load,seem fivem loading src problem
> need use __resource.lua instead for it

This is bullshit, works fine for me. Use latest artifacts.

**Comment by rex2630** [comment]
I made it plug and play for those who dont understand where to get html part -_- https://github.com/FM-RP/gcphone/releases/tag/2.22

**Comment by EbenSantuy** [comment]
help ?
image

**Comment by rex2630** [comment]
Reconnect. U cant restart the phone while its running

**Comment by NightcoreIsla** [comment]
> 救命 ？
i use sql default valut :
lpad(round(rand() * 99999,0),5,'0')
let sql generate phone number, and custom how long is it
then this first loading problem will also fix with sql generate

**Comment by EbenSantuy** [comment]
im alredy try the restart the phone and reconnect and still like that

**Comment by rex2630** [comment]
Omg, dont restart it!!!! And update your ESX!

**Comment by EbenSantuy** [comment]
im already update my esx im use es_extended 1.2

**Comment by EbenSantuy** [comment]
i dont why this happen? im already use your version and update all my esx my es_extended and reinstall the gcphone base and still this happen to my server

**Comment by nicoald295** [comment]
it works perfectly! only one problem is the phone is invisible.

**Comment by nicoald295** [comment]
> i dont why this happen? im already use your version and update all my esx my es_extended and reinstall the gcphone base and still this happen to my server

have you tried clearing the server cache?

**Comment by EbenSantuy** [comment]
yes im already . im tell my friends to join my server and check the phone number and on my friend the phone number showing but after my friend relog and check the phone number the phone number showing ###-####

**Comment by tmwatchanan** [comment]
This MR is so useful. It solves the bugs, for example, send invalid SMS and then the screen turns white (blank). This must be merged.

**Comment by mxnmsky** [comment]
i still have the problem @EbenSantuy has, how to i make it so it doesn't have ###-####

**Comment by EbenSantuy** [comment]
im still search to make it work @mxnmsky if you find the way to fix it you can tell on this topic

**Comment by nicoald295** [comment]
maybe I understand why the number is not generated try to delete this the least from this following line --- Pour les numero du style XXX-XXXX
- [[function getPhoneRandomNumber ()
    local numBase0 = math.random (100,999)
    local numBase1 = math.random (0.9999)
    local num = string.format ("% 03d-% 04d", numBase0, numBase1)

return num
end
-]]
--- Exemple pour les numero du style 06XXXXXXXX
- function getPhoneRandomNumber ()
- return '0' .. math.random (600000000,699999999)
- end
let me know if it works it should become so
--- Pour les style number XXX-XXXX
- [[function getPhoneRandomNumber ()
    local numBase0 = math.random (100,999)
    local numBase1 = math.random (0.9999)
    local num = string.format ("% 03d-% 04d", numBase0, numBase1)

return num
end
-]]
--- Exemple pour les numero du style 06XXXXXXXX
- function getPhoneRandomNumber ()
- return '0' .. math.random (600000000,699999999)
- end

**Comment by EbenSantuy** [comment]
anyone know how to fix the Number ###-#### the phone number already generate

**Comment by NightcoreIsla** [comment]
> anyone know how to fix the Number ###-#### the phone number already generate

geting phoneNumber "###-####" code in gcphone client event"esx_playerloaded"
this event will only active when player join with plugins "es_extended 1.2.0", then this event will trigger gcphone server event SQL SELECT phone number , then Send NUI phone number to HTML instead of ###-####
u can check that code and try fix
good luck

**Comment by Fluffyss** [comment]
image
im getting this error after all instructions here. Any help would be awesome :)

**Comment by NightcoreIsla** [comment]
> image
> im getting this error after all instructions here. Any help would be awesome :)
that is meaning "cb" is not function, ur code trying call cb as function, but it actually just a string
check whos calling , how to call, how to pass variable
like that
image

**Comment by Fluffyss** [comment]
> that is meaning "cb" is not function, ur code trying call cb as function, but it actually just a string
> check whos calling , how to call, how to pass variable
> like that
> image

emm how do you do the function? Because i deleted those "cb"'s etc. Now the  number isnt functioning anymore :P 
image

**Comment by ZachTaMere** [comment]
Hello, i'm novice at github how i can download your version of this phone ?
I downloaded it but it is some folder like src_htmlphone whose with them I don't know what to do

**Comment by raffycaccia** [comment]
just me, the phone does not display contacts and old messages from the database?

darkchat works properly though

**Comment by NightcoreIsla** [comment]
GO to SQL user.phone
set the default value to 

lpad(floor(round(rand(),3) * 99999),5,'0')
--

**Comment by NightcoreIsla** [comment]
> 只是我，電話不顯示數據庫中的聯繫人和舊消息？
> 
> 雖然暗聊可以正常工作

u can turn on Mysql-Async log, and check the query is working or not

**Comment by raffycaccia** [comment]
it still does not work, the data are correctly saved in the database but are not then read by gcphone

**Comment by raffycaccia** [comment]
I did some tests and the list of messages and contacts is displayed only if I send a message and then I delete it, in which case the whole list of messages is updated

**Comment by rex2630** [comment]
You cant restart the phone while being connected, omg....

**Comment by raffycaccia** [comment]
> You cant restart the phone while being connected, omg....

For me?

**Comment by rex2630** [comment]
It applies for all!!!

**Comment by gian77o** [comment]
> I did some tests and the list of messages and contacts is displayed only if I send a message and then I delete it, in which case the whole list of messages is updated
> 
> https://youtu.be/3k6k5AGR7zo


I got the same problem, where it doesn't visualize me the message or the calls if i don't write a new messg and dalte it. I haven't come to a conclusion for solve it. Can somone that as fixed it text me down the solution for make the telefon work as the previous version of esx

@rex2630 can you help me?

**Comment by rex2630** [comment]
It works just fine, I said the exact steps, so don't ask me again

**Comment by m0iises19** [comment]
I put all the steps of @rex2630 since we were both looking at the errors and everything is going well for me, you have to follow the steps and have esx updated

**Comment by xYouLL** [comment]
Why I get as number ###-#### even if the number is stored inside the database? I gave a look at the code and seems everything okay

**Comment by BrutalBirdie** [comment]
> I made it plug and play for those who dont understand where to get html part -_- https://github.com/FM-RP/gcphone/releases/tag/2.22

You are a true saint after going insane I guess :)

**Comment by EbenSantuy** [comment]
Fixed , Just Bad Configuration from me . Try To repositioning your server.cfg/resource.cfg

**Comment by blockhander3** [comment]
In the settings my phone number is ###-####, but when my friend checks his number is correct, but he has GTA on steam. How can i fix it?

**Comment by EbenSantuy** [comment]
yes sometime your friend have the number and when he restart he get the # number try to repositioning your cfg

**Comment by gabrielcalderon** [comment]
Are there plans to merge this?

**Comment by blockhander3** [comment]
@EbenSantuy Can you help, how reposition my cfg?

**Comment by gabrielcalderon** [comment]
@Gacha20 @Foen100 @N3MTV Are there plans to merge this or is this project dead?

**Comment by GlobbinTerpenes** [comment]
has anyone gotten the # to show?

**Comment by SW1FT** [comment]
Noticed `gcPhone:allUpdate` was removed from `server.lua`, I assume this was most likely unintentional. This breaks scripts like [esx_simcards](https://github.com/AshKetchumza/esx_simcards) that rely on this event to update phone information after a phone number change.

**Comment by camilopr11** [comment]
How to solve ###-#### phone number in settings?

**Comment by nicoald295** [comment]
> Come risolvere il numero di telefono ### - #### nelle 

> Come risolvere il numero di telefono ### - #### nelle impostazioni?

Download esx_cartesim

**Comment by Gannon001** [comment]
Je n'est pas GTA installé pour testé cette pull request.
Des personnes pour me confirmer que ces changements fonctionne Merci ;)

**Comment by rex2630** [comment]
No problem man, only problem is that u can't restart script while connected, but that's not anything u actually need, otherwise it works just fine, I'm using it for some time now :)

**Comment by Gannon001** [comment]
esx_cartesim is required or just optional ?

**Comment by rex2630** [comment]
Its just optional. Its an addon from another author to support multi sim, so multiple numbers with one character

**Comment by camilopr11** [comment]
@rex2630 can u help me? in settings the phone number is ###-#### but in database is saved correctly

**Comment by rex2630** [comment]
I dont know man how many times i should say how to install and run this. Just start the server with proper server.cfg and dont do anything exlecluding connecting to a server if u dont understand how things works...

**Pull request merged**
