### PR TITLE
Just my version for fxserver, use it if you want.

### PR DESCRIPTION
**Pull request by FrazzIe**
Just my version for fxserver, use it if you want.

### CODE REVIEW

**Comment by FrBillyD** [comment]
God ! Ty dude !

**Comment by FrazzIe** [comment]
time show right, but that's cause i don't really understand how it's displayed :?

**Comment by FrBillyD** [comment]
I've the same problem. We have tried to upgrade this to FX. It  was a failure... And I don't know the Vue.js logic...

**Comment by FrBillyD** [comment]
But, if you try to remove the phone tables in database, all phone is displayed...

**Comment by FrazzIe** [comment]
Well everything worked fine for me, just time xD
it either says http://prntscr.com/g3f9xq or sent NaN years ago

**Comment by FrBillyD** [comment]
Wow ! :D You touched something in the sources "src_htmlPhone"?

**Comment by FrazzIe** [comment]
I only touched the server.lua so and resource.lua

**Comment by FrBillyD** [comment]
I d'ont understand why. I try it today

**Comment by FrBillyD** [comment]
On which system you build the npm code ?

**Comment by FrBillyD** [comment]
Dude....YOU-ARE-AWESOME !
Just the problem with the date, all other it's ok. 😄

**Comment by MxWayGamer** [comment]
I try to use your phone for FXserver but when I push F2, the phone doesn't emerge. The player play animation and take his phone but no interface. I think it's due to "src_htmlphone" who doesn't appear in resource

**Comment by FrBillyD** [comment]
@MxWayGamer you need to compile src_htmlphone. Open readme in it.

**Comment by ExoticNx** [comment]
Can you send me you're files FrazzIe i cant get it to fucking work i have tried it makes me so bad

**Comment by Jay322** [comment]
has anyone compiled src_htmlphone i have tried and i cannot get it to work

**Comment by Jay322** [comment]
http://prntscr.com/gkafsg Got it to work but i don't have settings?

**Comment by Tonycalves** [comment]
Hey all ! Someone managed to install it? I get a lot of error when I compile it with npm ... I'm on windows, maybe that's the problem? Need some help, it would be really cool!

**Comment by szymsn** [comment]
Hey guys, i have a question. Where i need to type this: $ npm install to install src_htmlphone? thanks

**Pull request closed without merging**
