### PR TITLE
Compatibility with EssentialMode removal by es_extended

### PR DESCRIPTION
**Pull request by leroydev**

### CODE REVIEW

**Comment by polarim** [comment]
Still doesn't work, getPlayerId returns a nil value so nothing operates properly in the long-run.  :)

**Comment by rex2630** [comment]
One of the worst PR i ever seen. And u didnt even tested it :D

**Comment by leroydev** [comment]
@rex2630 nog a very constructive way to give feedback..
I got it working for myself but had some more local changes that weren't relevant for this PR, so I removed those changes. I might have removed too much.

I saw this PR as a good starting point, it's better than nothing in my opinion.

**Comment by rex2630** [comment]
Can u send me full code? Maybe u forgot something

**Comment by polarim** [comment]
I forgot what I've changed by now but I redid it for my own server personally.

Line 563/568 or whatever is irrelevant
local identifier = getPlayerID(source)

RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(source)
    local sourcePlayer = tonumber(source)
    local identifier = getPlayerID(source)

    getOrGeneratePhoneNumber(identifier, function (myPhoneNumber)
        TriggerClientEvent("gcPhone:myPhoneNumber", sourcePlayer, myPhoneNumber)
        TriggerClientEvent("gcPhone:contactList", sourcePlayer, getContacts(identifier))
        TriggerClientEvent("gcPhone:allMessage", sourcePlayer, getMessages(identifier))
    end)
end)


esx:playerLoaded pulls xPlayer automatically as second arg, so just change it
RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(source, xPlayer)
    local sourcePlayer = tonumber(source)
    local identifier = xPlayer.identifier

    getOrGeneratePhoneNumber(identifier, function (myPhoneNumber)
        TriggerClientEvent("gcPhone:myPhoneNumber", sourcePlayer, myPhoneNumber)
        TriggerClientEvent("gcPhone:contactList", sourcePlayer, getContacts(identifier))
        TriggerClientEvent("gcPhone:allMessage", sourcePlayer, getMessages(identifier))
    end)
end)

makes it move quicker.  I may have had a fluke of an issue when I tried it out at like 3am but it's w/e.

also
function getSourceFromIdentifier(identifier, cb)
    local users = ESX.Game.GetPlayers()
    for k , user in pairs(users) do
        if (user.getIdentifier ~= nil and user.getIdentifier() == identifier) or (user.identifier == identifier) then
            cb(k)
            return
        end
    end
    cb(nil)
end

might work a little better serverside as 

function getSourceFromIdentifier(identifier, cb)
	local xPlayers = ESX.GetPlayers()
	
	for i=1, #xPlayers, 1 do
		local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
		
		if(xPlayer.identifier ~= nil and xPlayer.identifier == identifier) or (xPlayer.identifier == identifier) then
			cb(xPlayer.source)
			return
		end
	end
	cb(nil)
end

idr if ESX.Game works serverside.  

one of the other issues with gcphone anyways is the weird "onclientresourcestart" function that tries to call gcPhone:allUpdate before xPlayer has even loaded so it fails out

can be negated somewhat by just adding 
		TriggerClientEvent('gcPhone:getBourse', sourcePlayer, getBourse())
		sendHistoriqueCall(sourcePlayer, myPhoneNumber)

to the esx:playerLoaded event

**Comment by leroydev** [comment]
@polarim @rex2630 My latest commit should fix that problem.

**Comment by rex2630** [comment]
Sorry, but this cant work. Can @polarim do separate PR or should i do it?

**Comment by Neofliix** [comment]
After trying id R * is well used for creating a contact but no number is assigned to the new player

FR: Après avoir essayé id R* est bien utilisé pour la création d'un contact mais aucun numéro est attribuer au nouveau joueur

**Comment by polarim** [comment]
Are you sure your latest commit fixes the onresourcestart issue?  I didn't think that could be held back until player is initialized. Or am I confused by your changes here.  I can test it out in a bit.

**Comment by leroydev** [comment]
@polarim it works for me, and as far as I can tell, it's the right event to wait for in this case.

Right after the player gets added to `ESX.Players`, `esx.playerLoaded` is fired: https://github.com/ESX-Org/es_extended/blob/73a818aed94a319d26ffb0a028ea6254334d99f5/server/main.lua#L173

If you check the sourcecode for GetPlayerFromId, it tries to find the player in `ESX.Players`: https://github.com/ESX-Org/es_extended/blob/ecbf340e391f1a3d91607d0e7d1b61917fbd86f5/server/functions.lua#L241

**Comment by m0iises19** [comment]
It works fine, you just have to do these steps too:

https://github.com/N3MTV/gcphone/pull/305

**Comment by m0iises19** [comment]
everything is fine, but it gives me this error

Sin título

the error refers to this line:

function getPlayerID(source)
    return ESX.GetPlayerFromId(source).identifier
end

**Comment by rex2630** [comment]
Nevermind, @leroydev doesnt know what he is even doing. I fixed this in my PR: https://github.com/N3MTV/gcphone/pull/305

**Comment by Rado236** [comment]
I still dont get an phone number generated after adding @rex2630 's code :(

**Comment by leroydev** [comment]
@rex2630 seems that even you make mistakes.. I'm just trying to help the community, please keep that in mind before venting your frustrations. ;)

**Comment by rex2630** [comment]
What mistakes? It works for me

**Pull request closed without merging**
